apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
    {{- if .Values.clusterRoleBinding.labels }}
      {{- toYaml .Values.clusterRoleBinding.labels | nindent 4 }}
    {{- end }}
  {{- if or .Values.clusterRoleBinding.annotations .Values.annotations }}
  annotations:
    {{- if .Values.clusterRoleBinding.annotations }}
      {{- toYaml .Values.clusterRoleBinding.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.annotations }}
      {{- toYaml .Values.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}